'use client';

import { ProductSpec, FounderContext, AnalysisResult } from './types';

const STORAGE_KEY = 'idea-analyzer-data';

interface StoredData {
  productSpec: Partial<ProductSpec>;
  founderContext: Partial<FounderContext>;
  result: AnalysisResult | null;
}

export function getStoredData(): StoredData {
  if (typeof window === 'undefined') {
    return { productSpec: {}, founderContext: {}, result: null };
  }

  try {
    const data = localStorage.getItem(STORAGE_KEY);
    if (data) {
      return JSON.parse(data);
    }
  } catch {
    // Ignore parse errors
  }

  return { productSpec: {}, founderContext: {}, result: null };
}

export function setStoredData(data: Partial<StoredData>): void {
  if (typeof window === 'undefined') return;

  const existing = getStoredData();
  const updated = { ...existing, ...data };
  localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
}

export function clearStoredData(): void {
  if (typeof window === 'undefined') return;
  localStorage.removeItem(STORAGE_KEY);
}

export function generateMarkdownExport(result: AnalysisResult, productSpec: Partial<ProductSpec>, founderContext: Partial<FounderContext>): string {
  const { VERDICT_CONFIG } = require('./types');
  const verdictConfig = VERDICT_CONFIG[result.verdict];

  return `# ${result.productName} Analysis

## The Verdict

${verdictConfig.emoji} **${verdictConfig.label}** — Score: ${result.overallScore.toFixed(1)}/10

${result.verdictSummary}

---

## Why It ${result.verdict === 'build' || result.verdict === 'build-with-changes' ? 'Works' : "Doesn't Work"}

### What's In Your Favor
${result.strengths.map(s => `- ${s}`).join('\n')}

### What You Need To Address
${result.mustAddress.map(m => `- ${m}`).join('\n')}

### What Could Kill It
${result.risks.map(r => `- ${r}`).join('\n')}

---

## The Numbers

| Metric | Value |
|--------|-------|
| Time to MVP | ${result.metrics.timeToMvp} |
| Time to First Revenue | ${result.metrics.timeToFirstRevenue} |
| Users Needed | ${result.metrics.usersNeeded} |
| Competition | ${result.metrics.competition} |

---

## Do This First (30 Days)

${result.actions.map((a, i) => `${i + 1}. [ ] ${a}`).join('\n')}

---

## Input Summary

### Product
- **Name:** ${productSpec.name || 'N/A'}
- **Category:** ${productSpec.category || 'N/A'}
- **Thesis:** ${productSpec.thesis || 'N/A'}
- **Target User:** ${productSpec.targetUser || 'N/A'}
- **Pricing:** ${productSpec.pricing || 'N/A'}

### Founder
- **Technical Skill:** ${founderContext.technicalSkill || 'N/A'}
- **Hours/Week:** ${founderContext.hoursPerWeek || 'N/A'}
- **Runway:** ${founderContext.runwayMonths || 'N/A'} months
- **Risk Tolerance:** ${founderContext.riskTolerance || 'N/A'}

---

*Generated by Idea Analyzer on ${new Date().toLocaleDateString()}*
`;
}
